exports.newWord = { // CAPITALIZE ALL
    wordList: [
        "APPLE",
        "ARTICHOKE",
        "APRICOT",
        "ASPARAGUS",
        "AVOCADO",
        "BANANA",
        "BEETROOT",
        "BLUEBERRY",
        "BROCCOLI",
        "BRUSSELS SPROUT",
        "BUTTERNUT SQUASH",
        "CANTALOUPE",
        "CARROT",
        "CHERRY",
        "CLEMENTINE",
        "CUMQUAT",
        "DATE",
        "EGGPLANT",
        "ELDERBERRY",
        "ENDIVE",
        "FAVA BEAN",
        "FENNEL",
        "FIG",
        "GARLIC",
        "GRAPE",
        "GRAPEFRUIT",
        "GREEN BEAN",
        "GUAVA",
        "HONEYDEW",
        "HUCKLEBERRY",
        "ICEBERG LETTUCE",
        "KIKI",
        "LEEK",
        "LEMON",
        "MANGO",
        "MANDARIN",
        "NECTARINE",
        "OLIVE",
        "ORANGE",
        "PEA",
        "PEANUT",
        "PEACH",
        "PEAR",
        "PEPPER",
        "PINEAPPLE",
        "PLUM",
        "PLUOT",
        "PUMPKIN",
        "QUINCE",
        "RADDISH",
        "RAISIN",
        "RASPBERRY",
        "RHUBARB",
        "STRAWBERRY",
        "SWEET POTATO",
        "TOMATO",
        "TURNIP",
        "WATERCRESS",
        "WATERMELON",
        "YAM",
        "ZUCCHINI"
    ], 
    hangman: [
        "hi"
    ]
};